config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :races do
    resources :bibs, only: [:new, :create]
  end

  resources :bibs, only: [:delete, :index, :update, :edit]

  devise_for :users
  resources :users, only: [:index]

  resources :conversations do
    resources :messages
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  get 'dashboard', to: 'pages#dashboard'
  get 'ressources', to: 'pages#ressources'
  get 'calcul_allure', to: 'pages#calcul_allure'
  get 'programme', to: 'pages#programme'
  get 'alimentation', to: 'pages#alimentation'
  get 'shop', to: 'pages#shop'
end

app/models/bib.rb
class Bib < ApplicationRecord
  belongs_to :user
  belongs_to :race
  monetize :price_cents
  validates :price, presence: true
  validates :available, presence: true
  enum available: {
    free: 1,
    unfree: 2
  }
end

app/controllers/bibs_controller.rb
class BibsController < ApplicationController
  before_action :set_bib, only: [:show, :edit, :update, :destroy]
  before_action :skip_authorization, only: :show
  before_action :skip_policy_scope, only: :index

  skip_before_action :authenticate_user!, only: :index
  skip_before_action :authenticate_user!, only: :show

  def index
    @bibs = Bib.all.where(available: "1")
  end

  def new
    @bib = Bib.new
    @races = Race.all
    authorize @bib
  end

  def create
    @bib = Bib.new(bib_params)
    authorize @bib
    @bib.user = current_user
    @bib.race_id = params[:bib][:race_id]
    if @bib.save
      @bib.race = @bib.sku
      redirect_to dashboard_path, notice: 'Votre dossard a bien été créée.'
    else
      render :new
    end
  end

  def show
    unless current_user == @bib.user
      if @bib.available == "unfree"
        redirect_to bibs_path, notice: 'Désolé, le dossard a déjà été vendu.'
      end
    end
  end

  def edit
    authorize @bib
  end

  def update
    authorize @bib
    @bib.update(bib_params)
    redirect_to bib_path(@bib)
  end

  def destroy
    authorize @bib
    @bib.destroy
    redirect_to bibs_path
  end

  private

  def set_bib
    @bib = Bib.find(params[:id])
  end

  def bib_params
    params.require(:bib).permit(:race_id, :price, :available)
  end
end

app/views/bibs/edit.html.erb
<div class="container">
  <div class="row mt-4 mb-4">
    <div class="col-xs-12 col-sm-8">
      <h2 class="mb-4">Modifiez votre dossard</h2>
      <hr>
      <%= simple_form_for @bib do |f| %>
        <%= f.input :race_id, as: :hidden, input_html: { value: params[:race_id] } %>
        <%= f.collection_select :race_id, Race.all, :id, :name %>
        <%= f.input :price_cents, as: :float, label: "Nouveau prix du dossard ?", input_html: { autocomplete: "price" } %>
        <%= f.input :available,
                        required: true,
                        input_html: { autocomplete: "available" },
                        as: :select, label: "Le dossard est-il toujours disponible ?",
                        collection: [['free', 'Oui'], ['unfree', 'Non']],
                        label_method: :second,
                        value_method: :first %>
        <%= f.submit "Modifier", class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="col-sm-4">
      <img class="rounded" width="100%" max-height="500" src="https://images.unsplash.com/photo-1508730328641-47c1616341b7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=930&q=80" alt="">
    </div>
  </div>
</div>
<%=  %>

app/views/bibs/index.html.erb
<div class="container">
  <div class="row w-100-custom">
    <div class="program-list mb-4 col-md-12">
      <h2 class="text-center mt-4 mb-4">Dossards en vente sur Rebib</h2>
        <% if @bibs.where(available: "free").count > 0 %>
          <div class="row">
            <% @bibs.where(available: "free").each do |bib| %>
              <div class="col-sm-3 col-md-3 mb-3">
                <%= link_to bib, class:"card-offer" do %>
                  <div class="card-offer">
                    <div class="card-offer-infos">
                      <h4><%= bib.race.name %></h4>
                      <p>📍 <%= bib.race.address.gsub(/([()])/,' \1 ') %></p>
                      <p>🙋🏼‍♂️ Dossard de <%= bib.user.first_name %></p>
                      <p><strong><%= humanized_money_with_symbol(bib.price) %></strong></p>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        <% else %>
        <p>Il n'y a plus de dossard en vente actuellement</p>
          <%= link_to "Vendez votre dossard", new_race_bib_path(Race.all), class:"btn btn-primary" %>
        <% end %>
    </div>
  </div>
</div>

app/views/bibs/new.html.erb
<div class="container">
  <div class="row mt-4 mb-4">
    <div class="col-xs-12 col-sm-8">
      <h2 class="mb-4">Vendez votre dossard</h2>
      <hr>
      <%= simple_form_for [@bib, Race.all] do |f| %>
        <%= f.input :race_id, as: :hidden, input_html: { value: params[:race_id] } %>
        <%= f.collection_select :race_id, Race.all, :id, :name, prompt: "Les courses déjà présentes sur Rebib", class: "form-dropdown" %>
        <%= f.input :price, as: :float, label: "Prix du dossard" %>
        <%= f.submit "Publier", class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="col-sm-4">
      <img class="rounded" width="100%" max-height="500" src="https://images.unsplash.com/photo-1508730328641-47c1616341b7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=930&q=80" alt="">
    </div>
  </div>
</div>
<%=  %>

app/views/bibs/show.html.erb
<div class="container">
  <div class="row mt-4 mb-4 d-flex justify-content-center text-center">
    <div class="col-xs-12 col-sm-6 bib p-4 m-4">
      <div class="mt-4">
        <span class="etiquette-bib px-4 py-2">Dossard</span>
      </div>
      <h2 class="mt-3 mb-3"><%= @bib.race.name %></h2>
      <div class="mt-4">
        <p>🏃🏽 Départ le <%= @bib.race.date.to_date.strftime('%d %B %Y') %></p>
      </div>
      <p>📍 <%= @bib.race.address.gsub(/([()])/,' \1 ') %></p>
      <p>🙋🏼‍♂️ Propriétaire de ce dossard : <%= @bib.user.first_name %></p>
      <p>📅 <%= @bib.created_at.strftime("Déposé le %d %B %Y") %></p>
      <p><strong><%= humanized_money_with_symbol(@bib.price) %></strong></p>
      <% if @bib.available == "unfree" %>
        <div class="mt-4 mb-4">
          <span class="etiquette-purchased px-4 py-2">Ce dossard n'est plus disponible</span>
        </div>
      <% end %>
      <% unless current_user == @bib.user %>
        <%# <%= form_tag orders_path do %>
          <%# <%= hidden_field_tag 'bib_id', @bib.id %>
          <%# <%= submit_tag 'Acheter', class: 'btn btn-primary' %>
        <%# <% end %>
        <%= link_to "Contacter le propriétaire", conversations_path(@conversation, sender_id: current_user, recipient_id: @bib.user.id), method: "post", class: "btn btn-white mb-3" %>
      <% else %>
        <%= link_to "Modifier mon dossard", edit_bib_path(@bib), class: "btn btn-white mb-3" %>
      <% end %>
      <div>
        <%= link_to "Retour à la course", race_path(@bib.race) %>
      </div>
    </div>
  </div>
</div>