config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :races do
    resources :bibs, only: [:new, :create]
  end

  resources :bibs, only: [:delete, :index, :update, :edit]

  devise_for :users
  resources :users, only: [:index]

  resources :conversations do
    resources :messages
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  get 'dashboard', to: 'pages#dashboard'
  get 'ressources', to: 'pages#ressources'
  get 'calcul_allure', to: 'pages#calcul_allure'
  get 'programme', to: 'pages#programme'
  get 'alimentation', to: 'pages#alimentation'
  get 'shop', to: 'pages#shop'
end

app/models/race.rb
class Race < ApplicationRecord
  include PgSearch::Model
  belongs_to :user
  has_many :bibs

  validates :name, presence: true
  validates :address, presence: true
  validates :address, presence: true
  validates :sport, presence: true
  validates :date, presence: true

  geocoded_by :address
  pg_search_scope :search_by_name,
                  against: [:name],
                  using: {
                    tsearch: { prefix: true }
                  }
  after_validation :geocode, if: :will_save_change_to_address?
  enum sport: {
    running: 0,
    bike: 1,
    triathlon: 2
  }
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: [:show, :edit, :update, :destroy]
  before_action :skip_authorization, only: :show
  before_action :skip_policy_scope, only: :index

  skip_before_action :authenticate_user!, only: :index
  skip_before_action :authenticate_user!, only: :show

  def index
    if params[:query].present?
      @races = Race.where("name ILIKE ?", "%#{params[:query]}%")
    elsif params[:sport]
      @races = Race.where(sport: params[:sport])
    else
      @races = Race.all
    end
    @markers = @races.geocoded.map do |race|
      {
        lat: race.latitude,
        lng: race.longitude,
        info_window: render_to_string(partial: "info_window", locals: { race: race }),
        image_url: helpers.image_path('running.png')
      }
    end
  end

  def new
    @race = Race.new
    authorize @race
  end

  def create
    @race = Race.new(race_params)
    @race.user = current_user
    authorize @race
    if @race.save
      redirect_to race_path(@race), notice: 'La course a bien été créée.'
    else
      render :new
    end
  end

  def show
  end

  def edit
    authorize @race
  end

  def update
    authorize @race
    @race.update(race_params)
    redirect_to race_path(@race)
  end

  def destroy
    authorize @race
    @race.destroy
    redirect_to races_path
  end

  private

  def set_race
    @race = Race.find(params[:id])
  end

  def race_params
    params.require(:race).permit(:name, :address, :date, :sport)
  end
end

app/views/races/_info_window.html.erb
<h5><%= race.name %></h5>
<p><%= race.address.gsub(/([()])/,' \1 ') %></p>

app/views/races/edit.html.erb
<div class="container col-md-6 my-5">
  <h2 class="text-center mt-4 mb-4">Add infos on <%= @race.name %> </h2>
</div>

app/views/races/index.html.erb
<div class="container">
  <div class="row w-100-custom">
    <div class="program-list mb-4 col-md-8">
      <div class="mt-4 mb-4">
        <%= render 'shared/searchbar' %>
      </div>
      <div class="mb-4">
        <%= link_to "Running", races_path(:sport=>"running"), class:"etiquette-filter px-4 py-2" %>
        <%= link_to "Bike", races_path(:sport=>"bike"), class:"etiquette-filter px-4 py-2" %>
        <%= link_to "Triathlon", races_path(:sport=>"triathlon"), class:"etiquette-filter px-4 py-2" %>
      </div>
      <% if @races.count > 0 %>
        <div class="row">
          <% @races.each do |race| %>
            <div class="col-sm-6 col-md-6 mb-3">
              <%= link_to race, class:"card-offer" do %>
                <div class="card-offer">
                  <div class="card-offer-infos">
                    <h4><%= race.name %></h4>
                    <% if race.sport == "running" %>
                      <p>🏃🏽 <%= race.date.to_date.strftime('%d %B %Y') %></p>
                    <% elsif race.sport == "bike" %>
                      <p>🚴🏼 <%= race.date.to_date.strftime('%d %B %Y') %></p>
                    <% elsif race.sport == "triathlon" %>
                      <p>🏊🏼‍♂️ <%= race.date.to_date.strftime('%d %B %Y') %></p>
                    <% end %>
                    <p>📍 <%= race.address.gsub(/([()])/,' \1 ') %></p>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      <% elsif params[:sport].present? %>
        <p>Aucune course <%= params[:sport] %> n'est disponible pour le moment.</p>
        <%= link_to "Ajouter une course", new_race_path, class:"btn btn-primary" %>
      <% else %>
      <p>Aucune course n'est disponible pour le moment.</p>
        <%= link_to "Ajouter une course", new_race_path, class:"btn btn-primary" %>
      <% end %>
    </div>
    <div class="col-md-4 map mt-4 mb-4"
              data-controller="mapbox"
              data-mapbox-markers-value="<%= @markers.to_json %>"
              data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/races/new.html.erb
<div class="container">
  <div class="row mt-4 mb-4">
    <div class="col-xs-12 col-sm-8">
      <h2 class="mb-4">Ajouter une course</h2>
      <hr>
      <%= simple_form_for @race do |f| %>
        <%= f.input :name, label: "Nom de la course" %>
        <%= f.input :sport,
                                wrapper_html: {class: "d-flex flex-column"},
                                required: false,
                                input_html: { autocomplete: "sport" },
                                as: :select, label: "Sport de l'évènement",
                                collection: [['running', 'Running'], ['bike', 'Vélo'], ['triathlon', 'Triathlon']],
                                label_method: :second, required: true,
                                value_method: :first %>
        <%= f.input :address,
                      input_html: { data: { geocoder_target: "address" }, class: "d-none" },
                      label: "Ville de la course",
                      wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
        <%= f.input :date, as: :date, html5: true, label: "Date de la course" %>
        <%= f.submit "Envoyer", class: "btn btn-flat" %>
      <% end %>
      <div class="mt-3 link">
        <%= link_to "Retour aux courses", races_path %>
      </div>
    </div>
    <div class="col-sm-4">
      <img class="rounded" width="100%" max-height="500" src="https://images.unsplash.com/photo-1560789363-cfa0cbf748f8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=750&q=80" alt="">
    </div>
  </div>
</div>

app/views/races/show.html.erb
<div class="container">
  <div class="row mt-4 mb-4">
    <div class="col-xs-12 col-sm-8">
      <h2 class="mb-4"> <%= @race.name %></h2>
      <span class="etiquette px-4 py-2"><%= @race.sport.capitalize %></span>
      <p class="mt-4">📅 Départ de la course le <%= @race.date.to_date.strftime('%d %B %Y') %></p>
      <p>📍 A lieu à <%= @race.address.gsub(/([()])/,' \1 ') %></p>
      <hr>
      <div class="row">
        <h4 class="mb-3">Dossards en vente</h4>
        <% if @race.bibs.where(available: "free").count > 0 %>
          <% @race.bibs.where(available: "free").each do |bib| %>
            <div class="col-sm-4 col-md-4 mb-3">
              <%= link_to race_bibs_path(@race), class:"card-offer" do %>
                <div class="card-offer">
                  <div class="card-offer-infos">
                    <h4>Dossard de <%= bib.user.first_name %></h4>
                    <p><%= bib.created_at.strftime("Déposé le %m %B %Y") %></p>
                    <%= link_to "Voir", race_bib_path(bib), class: "btn btn-primary" %>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% else %>
          <p>Il n'y a pas de dossards à vendre sur Rebib pour cette course.</p>
          <div class="col-sm-4">
            <%= link_to "Vendre un dossard", new_race_bib_path(@race), class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-sm-4">
      <img class="rounded" width="100%" max-height="500" src="https://images.unsplash.com/photo-1444491741275-3747c53c99b4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80" alt="">
    </div>
  </div>
</div>