config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :races do
    resources :bibs, only: [:new, :create]
  end

  resources :bibs, only: [:delete, :index, :update, :edit]

  devise_for :users
  resources :users, only: [:index]

  resources :conversations do
    resources :messages
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  get 'dashboard', to: 'pages#dashboard'
  get 'ressources', to: 'pages#ressources'
  get 'calcul_allure', to: 'pages#calcul_allure'
  get 'programme', to: 'pages#programme'
  get 'alimentation', to: 'pages#alimentation'
  get 'shop', to: 'pages#shop'
end

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1774&q=80);">
  <div class="container">
    <div class="logo-banner mb-3">
      <%= image_tag("rebib-logo-white.png") %>
    </div>
    <p>Vendez et achetez des dossards de course !</p>
    <%= link_to "Voir les courses", races_path, class: "btn btn-flat" %>
  </div>
</div>

app/views/shared/_banner_custom.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1528667819581-ca7e29e772bc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1771&q=80);">
  <div class="container">
    <h2>Une blessure ? Un désistement de dernière minute ?</h2>
    <p>Notre communauté d'athlètes est la pour acheter votre dossard</p>
    <%= link_to "Vendre mon dossard", new_race_bib_path(Race.all), class: "btn btn-flat" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class = "footer">
  <div class="container py-3">
    <div class="row py-4">
      <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
        <h6 class="text-uppercase font-weight-bold mb-4">COURSES</h6>
        <ul class="list-unstyled mb-0">
          <li class="mb-2"><%= link_to("Liste des courses", races_path) %></li>
          <li class="mb-2"><%= link_to("Ajouter une course", new_race_path) %></li>
          <li class="mb-2"><%= link_to("Mes dossards", dashboard_path) %></li>
          <li class="mb-2"><%= link_to("Vendre mon dossard", new_race_bib_path(Race.all)) %></li>
        </ul>
      </div>
      <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
        <h6 class="text-uppercase font-weight-bold mb-4 ">REBIB</h6>
        <ul class="list-unstyled mb-0">
          <li class="mb-2"><a href="#" class="">Notre blog</a></li>
          <li class="mb-2"><%= link_to("Se connecter", new_user_session_path) %></li>
          <li class="mb-2"><%= link_to("S'inscrire", new_user_registration_path) %></li>
        </ul>
      </div>
      <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
        <h6 class="text-uppercase font-weight-bold mb-4 ">RESSOURCES</h6>
          <ul class="list-unstyled mb-0">
            <li class="mb-2"><a href="#" class="">Calcul allure</a></li>
            <li class="mb-2"><a href="#" class="">Programmes</a></li>
            <li class="mb-2"><a href="#" class="">Alimentation</a></li>
            <li class="mb-2"><a href="#" class="">Shop</a></li>
          </ul>
      </div>
      <div class="col-lg-4 col-md-6 mb-lg-0">
        <h6 class="text-uppercase font-weight-bold mb-4 border-bottom border-light ">Newsletter</h6>
        <p class="mb-4 ">Suivez-vous pour être tenu informé des prochaines courses</p>
        <div class="p-1 rounded border mb-4">
          <div class="input-group">
            <input type="email" placeholder="Entrez votre adresse e-mail" aria-describedby="button-addon1" class="form-control border-0 shadow-0">
            <div class="input-group-append">
              <button id="button-addon1" type="submit" class="btn btn-link"><i class="fa fa-paper-plane"></i></button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <%= image_tag("rebib-logo-blue.png") %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Accueil", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Courses", races_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Dossards", bibs_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Ressources", ressources_path, class: "nav-link" %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src= "http://sanjaymotels.com/wp-content/uploads/2019/01/testimony.png"/>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <%= link_to "Tableau de bord", dashboard_path, class: "text-decoration-none dropdown-item" %>
                  <%= link_to "Messages", conversations_path, class: "text-decoration-none dropdown-item" %>
                  <%= link_to "Vendre un dossard", new_race_bib_path(Race.all), class: "text-decoration-none dropdown-item" %>
                  <%= link_to "Éditer mon profil",edit_user_registration_path(current_user),class: "text-decoration-none dropdown-item" %>
                  <%= link_to "Se déconnecter", destroy_user_session_path, :method => :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item dropdown">
              <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src= "http://sanjaymotels.com/wp-content/uploads/2019/01/testimony.png"/>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <%= link_to "S'inscrire", new_user_registration_path, class: "text-decoration-none dropdown-item" %>
                  <%= link_to "Se connecter", user_session_path, class: "text-decoration-none dropdown-item" %>
              </div>
            </li>
          <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_ressources.html.erb
 <div class="cards mb-5 mt-5">
    <%= link_to calcul_allure_path do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1593198805047-b97ea2348680?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1674&q=80)">
        Calcul allure
      </div>
    <% end %>
    <%= link_to programme_path do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1502904550040-7534597429ae?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2800&q=80)">
        Programmes
      </div>
    <% end %>
    <%= link_to alimentation_path do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1490645935967-10de6ba17061?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1753&q=80)">
        Alimentation
      </div>
    <% end %>
    <%= link_to shop_path do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1610969770059-7084269fa3be?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80)">
        Shop
      </div>
    <% end %>
  </div>

app/views/shared/_searchbar.html.erb
<%= simple_form_for :search, url: races_path, method: :get do %>
  <div class="search-form-control form-group mb-3">
    <%= text_field_tag :query, params[:query], class: "form-control string required", placeholder: "Trouver une course" %>
    <%= submit_tag "Rechercher", type: "submit", name: "button", class: "btn btn-flat" %>
  </div>
<% end %>