config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :races do
    resources :bibs, only: [:new, :create]
  end

  resources :bibs, only: [:delete, :index, :update, :edit]

  devise_for :users
  resources :users, only: [:index]

  resources :conversations do
    resources :messages
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  get 'dashboard', to: 'pages#dashboard'
  get 'ressources', to: 'pages#ressources'
  get 'calcul_allure', to: 'pages#calcul_allure'
  get 'programme', to: 'pages#programme'
  get 'alimentation', to: 'pages#alimentation'
  get 'shop', to: 'pages#shop'
end

app/views/pages/calcul_allure.html.erb
<div class="container">
  <h2 class="mt-4 text-center">Calcul d'allure</h2>
  <div class="text-center">
    <h4>Préparez votre allure de course</h4>
    <%= form_with do |form| %>
      <%= form.label :distance, "Vous préparez une course de ? (en km)" %>
      <%= form.select :distance, [["Marathon", "MA"], ["Semi-marathon", "SM"], ["10km", "10"]] %>
    <% end %>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="container">

  <h2 class="mt-4 mb-4 text-center"> Bonjour <%= current_user.first_name %> 👋🏼</h2>

  <div class="container mt-4 mb-4" data-controller="switch-tab">

    <ul class="list-inline tabs-underlined" id="dashboard-tab">
      <%# <li>
        <h4>
          <a href="" class="tab-underlined active" data-action="click->switch-tab#switch" data-switch-tab-target="tab" data-tab-name="orders-user">Mes réservations</a>
        </h4>
      </li> %>
      <li>
        <h4>
        <a href="" class="tab-underlined active" data-action="click->switch-tab#switch" data-switch-tab-target="tab" data-tab-name="bibs-user">Mes dossards</a>
        </h4>
      </li>
    </ul>

    <div class="tab-content">

        <%# <div class="cards-dashboard" id="your-orders" data-switch-tab-target="content" data-tab-name="orders-user">
          <% current_user.orders.each do |order| %>
            <%# <div class="mb-3"> %>
              <%# <%= link_to order, class:"card-offer" do %>
                <%# <div class="card-offer"> %>
                  <%# <div class="card-offer-infos"> %>
                    <%# <h4><%= order.bib.race.name %>
                    <%# <p><strong>Le <%= order.bib.race.date.to_date.strftime('%d %B %Y') %>
                    <%# <p>📍 <%= order.bib.race.address.gsub(/([()])/,' \1 ') %>
                    <%# <%= link_to "Voir", order_path(order), class: "btn btn-primary" %>
                  <%# </div> %>
                <%# </div> %>
              <%# <% end %>
            <%# </div> %>
          <%# <% end %>
        <%# </div> %>

        <% if current_user.bibs.count > 0 %>
          <div class="cards-dashboard" id="your-bibs" data-switch-tab-target="content" data-tab-name="bibs-user">
              <% current_user.bibs.reverse.each do |bib| %>
                <div class="mb-3">
                  <%= link_to bib, class:"card-offer" do %>
                    <div class="card-offer">
                      <div class="card-offer-infos">
                        <h4><%= bib.race.name %></h4>
                        <p>Départ le : <%= bib.race.date.to_date.strftime('%d/%m/%Y') %></p>
                        <p>📍 <%= bib.race.address.gsub(/([()])/,' \1 ') %></p>
                        <div class="etiquette-status px-2 py-2 mb-2">
                          <% if bib.available == "unfree" %>
                            <p>Plus disponible</p>
                          <% else %>
                            <p>En vente</p>
                          <% end %>
                        </div>
                      </div>
                    </div>
                  <% end %>
                </div>
              <% end %>
          </div>
        <% else %>
          <div class="text-center mt-5">
            <p>Vous n'avez pas encore de dossard en vente sur Rebib ? Profitez-en !</p>
            <%= link_to "Vendre un dossard", new_race_bib_path(Race.all), class:"btn btn-primary" %>
          </div>
        <% end %>

    </div>

  </div>
</div>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>
<div class="container mt-4 mb-4">
  <h2 class="text-center mb-4">Courses à venir</h2>
  <div class="row">
    <% @races.first(9).each do |race| %>
      <div class="col-sm-4 col-md-4 mb-3">
        <%= link_to race, class:"card-offer" do %>
          <div class="card-offer">
            <div class="card-offer-infos">
              <h4><%= race.name %></h4>
              <p>Départ le <%= race.date.to_date.strftime('%d %B %Y') %></p>
              <p>📍 <%= race.address.gsub(/([()])/,' \1 ') %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <h2 class="text-center mb-4">Ressources</h2>
  <%= render 'shared/ressources' %>
</div>
<%= render 'shared/banner_custom' %>

app/views/pages/ressources.html.erb
<div class="container">
  <%= render 'shared/ressources' %>
</div>